# Generated by Django 3.2.4 on 2022-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_answer_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=' राष्ट्रिय', max_length=20),
            preserve_default=False,
        ),
    ]
