# Generated by Django 3.2.4 on 2022-03-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
    ]
