# Generated by Django 3.2.4 on 2022-03-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='private_post',
            field=models.BooleanField(default=False),
        ),
    ]
