# Generated by Django 3.2.4 on 2022-03-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_private_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private_post',
            field=models.BooleanField(default=False),
        ),
    ]
