# Generated by Django 3.2.4 on 2022-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_private_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='use_preeti',
            field=models.BooleanField(default=False),
        ),
    ]
