# Generated by Django 3.2.1 on 2021-05-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_userprofile_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pofile_pic',
            new_name='profile_pic',
        ),
    ]
